---
#

- name: Install nginx with apt
  apt:
   name: nginx
   update_cache: yes
 
- name: start nginx
  service:
      name: nginx
      state: started

- name: copy the nginx config file and restart nginx
  copy:
    src: /home/ubuntu/elk-playbook-project/roles/nginx/tasks/static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
  become: yes
- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
