- name: Update nginx conf file
  blockinfile:
    path: /etc/logstash/conf.d/nginx-01.conf
    block: |
        input {
          beats {
            port => 5044
            host => "0.0.0.0"
          }
        }

        filter {
          grok {
            patterns_dir => "/etc/logstash/patterns"
            match => { "message" => "%{NGINX_ACCESS}" }
            remove_tag => ["_grokparsefailure"]
            add_tag => ["nginx_access"]
          }
          mutate {
            convert => ["response", "integer"]
            convert => ["bytes", "integer"]
            convert => ["responsetime", "float"]
        }
          geoip {
            source => "clientip"
            add_tag => [ "nginx-geoip" ]
        }
          useragent {
            source => "agent"
        }

        }

        output {
          elasticsearch {
            hosts => ["ec2-3-9-117-225.eu-west-2.compute.amazonaws.com:9200"]
            index => "logstash-%{+YYYY.MM.dd}"
          }
        stdout { codec => rubydebug }
}


- name: Creating a file with content
  copy:
    dest: /etc/logstash/patterns/nginx
    content: |
      %{IPORHOST:clientip} (?:-|(%{WORD}.%{WORD})) %{USER:ident} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)

- name: Update filebeat config
  blockinfile:
    dest: /etc/filebeat/filebeat.yml
    block: |
      filebeat.inputs:
      - type: log
        paths:
          - /var/log/nginx/*.log
        exclude_files: ['\.gz$']

      output.logstash:
        hosts: ["localhost:5044"]




