- name: Update nginx conf file
  blockinfile:
    path: /etc/logstash/conf.d/nginx-01.conf
    block: |
      input {
        beats {
          port => 5044
          host => "0.0.0.0"
        }
      }

      filter {
      grok {
        match => [ "message" , "%{COMBINEDAPACHELOG}+%{GREEDYDATA:extra_fields}"]
        overwrite => [ "message" ]
      }
      mutate {
        convert => ["response", "integer"]
        convert => ["bytes", "integer"]
        convert => ["responsetime", "float"]
      }
      geoip {
        source => "clientip"
        target => "geoip"
        add_tag => [ "nginx-geoip" ]
      }
      date {
        match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
        remove_field => [ "timestamp" ]
      }
      useragent {
        source => "agent"
      }
      }

      output {
        elasticsearch {
          hosts => ["http://ec2-18-133-220-173.eu-west-2.compute.amazonaws.com:9200"]
          index => "logstash-%{+YYYY.MM.dd}"
        }
      stdout { codec => rubydebug }
      }




- name: Update filebeat config
  blockinfile:
    dest: /etc/filebeat/filebeat.yml
    block: |
      filebeat.inputs:
      - type: log
        paths:
          - /var/log/nginx/*.log
        exclude_files: ['\.gz$']

      output.logstash:
        hosts: ["localhost:5044"]

