---


- name: Restart logstash
  service:
    name: logstash
    state: restarted


- name: Restart kibana
  service:
    name: kibana
    state: restarted

- name: Restart metricbeat
  service:
    name: filebeat
    state: restarted

- name: Restart elasticservice
  service:
    name: elasticsearch
    state: restarted


